### ISSUE TITLE
Decide on approach to nautical charts

### ISSUE THREAD

**Issue by tomheinrichs** [gina-alaska/nasa-ace#45] opened 2016-09-15 22:25 UTC

**Comment by tomheinrichs** [comment] 2016-09-15 22:26
Use GINA's existing WMS of NOAA charts? Regardless, need to mark as "not for navigation".

**Comment by teknofire** [comment] 2016-11-09 20:29
Need to decide if we want to implement this using the GINA WMS or work to integrate the NOAA Vector services.

**Comment by vlraymond** [comment] 2017-04-19 19:00
duplicate of 181

**Closed** 2017-04-19 19:00 UTC
Labels: Medium Priority, question
